<?php

/**
 * @file
 * Contains userpoints.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function userpoints_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Help for the userpoints module.
    case 'help.page.userpoints':
      $output = '';
      $output .= nl2br(file_get_contents(__DIR__ . '/README.md'));
      return $output;

    default:
  }
}
